"""make prompt_text optional and add title to dream

Revision ID: 4f1e58286ebb
Revises: af7fc0ad7159
Create Date: 2025-12-29 13:47:31.125452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f1e58286ebb'
down_revision: Union[str, Sequence[str], None] = 'af7fc0ad7159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dreams', sa.Column('title', sa.String(length=255), nullable=True))
    op.alter_column('dreams', 'prompt_text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dreams', 'prompt_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('dreams', 'title')
    # ### end Alembic commands ###
