"""refactor_media_and_add_youtube_url

Revision ID: af7fc0ad7159
Revises: 8f6f1cff722a
Create Date: 2025-12-28 23:51:34.188341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7fc0ad7159'
down_revision: Union[str, Sequence[str], None] = '8f6f1cff722a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dream_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dream_id', sa.Integer(), nullable=False),
    sa.Column('media_url', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dream_media_dream_id'), 'dream_media', ['dream_id'], unique=False)
    op.create_index(op.f('ix_dream_media_id'), 'dream_media', ['id'], unique=False)
    op.drop_index(op.f('ix_dream_images_dream_id'), table_name='dream_images')
    op.drop_index(op.f('ix_dream_images_id'), table_name='dream_images')
    op.drop_table('dream_images')
    op.add_column('dreams', sa.Column('youtube_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dreams', 'youtube_url')
    op.create_table('dream_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dream_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], name=op.f('dream_images_dream_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dream_images_pkey'))
    )
    op.create_index(op.f('ix_dream_images_id'), 'dream_images', ['id'], unique=False)
    op.create_index(op.f('ix_dream_images_dream_id'), 'dream_images', ['dream_id'], unique=False)
    op.drop_index(op.f('ix_dream_media_id'), table_name='dream_media')
    op.drop_index(op.f('ix_dream_media_dream_id'), table_name='dream_media')
    op.drop_table('dream_media')
    # ### end Alembic commands ###
